# Generated by Django 2.0.1 on 2018-01-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='createdby',
            new_name='createby',
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('PR', 'Programming'), ('NT', 'Networking'), ('PC', 'PC Technichian')], default='PC', max_length=2, verbose_name='Coursework'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created_Date'),
        ),
    ]
